[build]
  publish = "dist/tcsa/browser"  # Adjust this path to your Angular app's output directory
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/json-server"
  status = 200